-- Issue #2873: least-privilege dflow_prod service identities. The expected
-- matrix below is the exact grant set; the catalog must match it in both
-- directions, and each runtime identity must be refused everything else.
begin;

create temporary table t2873_expected(grantee text, kind text, name text, priv text) on commit drop;
insert into t2873_expected values
  ('designflow_prod_backend_grants','table','AdditionalUserEmail','SELECT'),
  ('designflow_prod_backend_grants','table','AdditionalUserEmail','INSERT'),
  ('designflow_prod_backend_grants','table','AuditLog','SELECT'),
  ('designflow_prod_backend_grants','table','AuditLog','INSERT'),
  ('designflow_prod_backend_grants','table','FOBCountry','SELECT'),
  ('designflow_prod_backend_grants','table','FOBCountry','INSERT'),
  ('designflow_prod_backend_grants','table','FOBCountry','UPDATE'),
  ('designflow_prod_backend_grants','table','Factory','SELECT'),
  ('designflow_prod_backend_grants','table','Factory','INSERT'),
  ('designflow_prod_backend_grants','table','Factory','UPDATE'),
  ('designflow_prod_backend_grants','table','GridAccessLevel','SELECT'),
  ('designflow_prod_backend_grants','table','GridAccessLevel','INSERT'),
  ('designflow_prod_backend_grants','table','GridAccessLevel','UPDATE'),
  ('designflow_prod_backend_grants','table','GridChildrenLayout','SELECT'),
  ('designflow_prod_backend_grants','table','GridChildrenLayout','INSERT'),
  ('designflow_prod_backend_grants','table','GridChildrenLayoutOrder','SELECT'),
  ('designflow_prod_backend_grants','table','GridChildrenLayoutOrder','INSERT'),
  ('designflow_prod_backend_grants','table','GridChildrenLayoutOrder','UPDATE'),
  ('designflow_prod_backend_grants','table','GridLayout','SELECT'),
  ('designflow_prod_backend_grants','table','GridLayout','INSERT'),
  ('designflow_prod_backend_grants','table','GridLayout','UPDATE'),
  ('designflow_prod_backend_grants','table','GridViewState','SELECT'),
  ('designflow_prod_backend_grants','table','GridViewState','INSERT'),
  ('designflow_prod_backend_grants','table','GridViewState','UPDATE'),
  ('designflow_prod_backend_grants','table','RFQContainer','SELECT'),
  ('designflow_prod_backend_grants','table','RFQContainer','INSERT'),
  ('designflow_prod_backend_grants','table','RFQContainer','UPDATE'),
  ('designflow_prod_backend_grants','table','RFQGroup','SELECT'),
  ('designflow_prod_backend_grants','table','RFQGroup','INSERT'),
  ('designflow_prod_backend_grants','table','RFQGroup','UPDATE'),
  ('designflow_prod_backend_grants','table','RFQItem','SELECT'),
  ('designflow_prod_backend_grants','table','RFQItem','INSERT'),
  ('designflow_prod_backend_grants','table','RFQItem','UPDATE'),
  ('designflow_prod_backend_grants','table','RFQItem','DELETE'),
  ('designflow_prod_backend_grants','table','RFQItemStatus','SELECT'),
  ('designflow_prod_backend_grants','table','RFQStep','SELECT'),
  ('designflow_prod_backend_grants','table','RFQStep','UPDATE'),
  ('designflow_prod_backend_grants','table','RFQVendor','SELECT'),
  ('designflow_prod_backend_grants','table','RFQVendor','INSERT'),
  ('designflow_prod_backend_grants','table','RFQVendor','UPDATE'),
  ('designflow_prod_backend_grants','table','RFQVendor','DELETE'),
  ('designflow_prod_backend_grants','table','RFQWhse','SELECT'),
  ('designflow_prod_backend_grants','table','RFQWhse','UPDATE'),
  ('designflow_prod_backend_grants','table','RolePermissions','SELECT'),
  ('designflow_prod_backend_grants','table','RolePermissions','INSERT'),
  ('designflow_prod_backend_grants','table','RolePermissions','UPDATE'),
  ('designflow_prod_backend_grants','table','Roles','SELECT'),
  ('designflow_prod_backend_grants','table','SeasonCode','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedDetail','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedDetail','INSERT'),
  ('designflow_prod_backend_grants','table','StandardizedGroup','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedGroup','INSERT'),
  ('designflow_prod_backend_grants','table','StandardizedProductElement','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedProductElement','INSERT'),
  ('designflow_prod_backend_grants','table','StandardizedProductElement','UPDATE'),
  ('designflow_prod_backend_grants','table','StandardizedProductElementValue','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedProductType','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedProductType','INSERT'),
  ('designflow_prod_backend_grants','table','StandardizedSize','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedSize','INSERT'),
  ('designflow_prod_backend_grants','table','StandardizedSize','UPDATE'),
  ('designflow_prod_backend_grants','table','StandardizedVendor','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedVendor','INSERT'),
  ('designflow_prod_backend_grants','table','StandardizedVendor','UPDATE'),
  ('designflow_prod_backend_grants','table','StandardizedVersion','SELECT'),
  ('designflow_prod_backend_grants','table','StandardizedVersion','INSERT'),
  ('designflow_prod_backend_grants','table','UDFComponent','SELECT'),
  ('designflow_prod_backend_grants','table','UDFElement','SELECT'),
  ('designflow_prod_backend_grants','table','UDFElementType','SELECT'),
  ('designflow_prod_backend_grants','table','UDFGroup','SELECT'),
  ('designflow_prod_backend_grants','table','UDFTable','SELECT'),
  ('designflow_prod_backend_grants','table','UIElements','SELECT'),
  ('designflow_prod_backend_grants','table','UIElements','INSERT'),
  ('designflow_prod_backend_grants','table','age_group','SELECT'),
  ('designflow_prod_backend_grants','table','age_group','INSERT'),
  ('designflow_prod_backend_grants','table','age_group','UPDATE'),
  ('designflow_prod_backend_grants','table','ai_cache_events','SELECT'),
  ('designflow_prod_backend_grants','table','ai_cache_events','INSERT'),
  ('designflow_prod_backend_grants','table','app_settings','SELECT'),
  ('designflow_prod_backend_grants','table','app_settings','INSERT'),
  ('designflow_prod_backend_grants','table','app_settings','UPDATE'),
  ('designflow_prod_backend_grants','table','art_types','SELECT'),
  ('designflow_prod_backend_grants','table','art_types','INSERT'),
  ('designflow_prod_backend_grants','table','art_types','UPDATE'),
  ('designflow_prod_backend_grants','table','artist_types','SELECT'),
  ('designflow_prod_backend_grants','table','artist_types','INSERT'),
  ('designflow_prod_backend_grants','table','artist_types','UPDATE'),
  ('designflow_prod_backend_grants','table','artists','SELECT'),
  ('designflow_prod_backend_grants','table','artists','INSERT'),
  ('designflow_prod_backend_grants','table','artists','UPDATE'),
  ('designflow_prod_backend_grants','table','auth_token','SELECT'),
  ('designflow_prod_backend_grants','table','auth_token','INSERT'),
  ('designflow_prod_backend_grants','table','auth_token','UPDATE'),
  ('designflow_prod_backend_grants','table','comments','SELECT'),
  ('designflow_prod_backend_grants','table','comments','INSERT'),
  ('designflow_prod_backend_grants','table','comments','UPDATE'),
  ('designflow_prod_backend_grants','table','comments','DELETE'),
  ('designflow_prod_backend_grants','table','companyCode','SELECT'),
  ('designflow_prod_backend_grants','table','customers','SELECT'),
  ('designflow_prod_backend_grants','table','customers','INSERT'),
  ('designflow_prod_backend_grants','table','customers','UPDATE'),
  ('designflow_prod_backend_grants','table','customers','DELETE'),
  ('designflow_prod_backend_grants','table','deliveryLocation','SELECT'),
  ('designflow_prod_backend_grants','table','deliveryLocation','INSERT'),
  ('designflow_prod_backend_grants','table','deliveryLocation','UPDATE'),
  ('designflow_prod_backend_grants','table','divisionCode','SELECT'),
  ('designflow_prod_backend_grants','table','email_logs','INSERT'),
  ('designflow_prod_backend_grants','table','grid_cell_notes','SELECT'),
  ('designflow_prod_backend_grants','table','grid_cell_notes','INSERT'),
  ('designflow_prod_backend_grants','table','grid_cell_notes','UPDATE'),
  ('designflow_prod_backend_grants','table','grid_cell_notes','DELETE'),
  ('designflow_prod_backend_grants','table','itemAttachment','SELECT'),
  ('designflow_prod_backend_grants','table','itemAttachment','INSERT'),
  ('designflow_prod_backend_grants','table','itemAttachment','UPDATE'),
  ('designflow_prod_backend_grants','table','itemAttachment','DELETE'),
  ('designflow_prod_backend_grants','table','itemDepth','SELECT'),
  ('designflow_prod_backend_grants','table','itemDepth','INSERT'),
  ('designflow_prod_backend_grants','table','itemDepth','UPDATE'),
  ('designflow_prod_backend_grants','table','itemDepth','DELETE'),
  ('designflow_prod_backend_grants','table','itemHeader','SELECT'),
  ('designflow_prod_backend_grants','table','itemHeader','UPDATE'),
  ('designflow_prod_backend_grants','table','itemSize','SELECT'),
  ('designflow_prod_backend_grants','table','itemSize','INSERT'),
  ('designflow_prod_backend_grants','table','itemSize','UPDATE'),
  ('designflow_prod_backend_grants','table','itemSize','DELETE'),
  ('designflow_prod_backend_grants','table','item_character_associations','SELECT'),
  ('designflow_prod_backend_grants','table','item_user_assignment','SELECT'),
  ('designflow_prod_backend_grants','table','item_workflow_action','SELECT'),
  ('designflow_prod_backend_grants','table','licenseList','SELECT'),
  ('designflow_prod_backend_grants','table','licenseList','INSERT'),
  ('designflow_prod_backend_grants','table','licenseList','UPDATE'),
  ('designflow_prod_backend_grants','table','merchGroup','SELECT'),
  ('designflow_prod_backend_grants','table','merchGroup','UPDATE'),
  ('designflow_prod_backend_grants','table','merchGroupHeaders','SELECT'),
  ('designflow_prod_backend_grants','table','properties_and_characters','SELECT'),
  ('designflow_prod_backend_grants','table','property_character_associations','SELECT'),
  ('designflow_prod_backend_grants','table','quote_auth_token','SELECT'),
  ('designflow_prod_backend_grants','table','quote_auth_token','INSERT'),
  ('designflow_prod_backend_grants','table','quote_auth_token','UPDATE'),
  ('designflow_prod_backend_grants','table','user_notification','SELECT'),
  ('designflow_prod_backend_grants','table','user_notification','INSERT'),
  ('designflow_prod_backend_grants','table','user_notification','UPDATE'),
  ('designflow_prod_backend_grants','table','user_notification','DELETE'),
  ('designflow_prod_backend_grants','table','users','SELECT'),
  ('designflow_prod_backend_grants','table','users','INSERT'),
  ('designflow_prod_backend_grants','table','users','UPDATE'),
  ('designflow_prod_backend_grants','table','vendor','SELECT'),
  ('designflow_prod_backend_grants','table','vendor','INSERT'),
  ('designflow_prod_backend_grants','table','vendor','UPDATE'),
  ('designflow_prod_backend_grants','table','vendorGroup','SELECT'),
  ('designflow_prod_backend_grants','table','vendorGroup','INSERT'),
  ('designflow_prod_backend_grants','table','vendorGroup','UPDATE'),
  ('designflow_prod_backend_grants','table','vendorGroup','DELETE'),
  ('designflow_prod_backend_grants','view','item_workflow_handoff','SELECT'),
  ('designflow_prod_backend_grants','sequence','AdditionalUserEmail_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','AuditLog_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','FOBCountry_FOBCountry_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','Factory_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','GridChildrenLayoutOrder_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','GridChildrenLayout_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','GridViewState_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RFQContainer_RFQContainer_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RFQCustomLayout_RFQCustomLayout_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RFQGroup_RFQGroup_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RFQItem_rfqItem_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RFQLayout_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RFQVendor_RFQVendor_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','RolePermissions_Id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedDetail_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedGroup_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedProductElement_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedProductType_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedSize_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedVendor_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','StandardizedVersion_id_seq1','USAGE'),
  ('designflow_prod_backend_grants','sequence','UIElements_Id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','deliveryLocation_deliveryLocation_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','itemDepth__id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','itemPackage_item_package_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','itemSize_itemSize_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','licenseList_licenseList_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','signUpToken_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','vendorGroup_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','age_group_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','art_types_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','artist_types_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','artists_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','auth_token_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','comments_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','customers_customers_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','email_logs_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','user_notification_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','users_id_seq','USAGE'),
  ('designflow_prod_backend_grants','sequence','vendor_vendor_id_seq','USAGE'),
  ('designflow_prod_backend_grants','function','record_item_workflow_action','EXECUTE'),
  ('designflow_prod_backend_grants','function','set_item_user_assignment','EXECUTE'),
  ('designflow_prod_item_master_grants','table','AuditLog','INSERT'),
  ('designflow_prod_item_master_grants','table','GridAccessLevel','SELECT'),
  ('designflow_prod_item_master_grants','table','GridLayout','SELECT'),
  ('designflow_prod_item_master_grants','table','LicenseFeedBacks','SELECT'),
  ('designflow_prod_item_master_grants','table','LicensingTime','SELECT'),
  ('designflow_prod_item_master_grants','table','ProdOrderDetail','SELECT'),
  ('designflow_prod_item_master_grants','table','RFQItem','SELECT'),
  ('designflow_prod_item_master_grants','table','SeasonCode','SELECT'),
  ('designflow_prod_item_master_grants','table','art_piece','SELECT'),
  ('designflow_prod_item_master_grants','table','art_piece','INSERT'),
  ('designflow_prod_item_master_grants','table','art_piece','DELETE'),
  ('designflow_prod_item_master_grants','table','art_piece_attachment','SELECT'),
  ('designflow_prod_item_master_grants','table','art_piece_attachment','INSERT'),
  ('designflow_prod_item_master_grants','table','art_piece_attachment','DELETE'),
  ('designflow_prod_item_master_grants','table','customers','SELECT'),
  ('designflow_prod_item_master_grants','table','divisionCode','SELECT'),
  ('designflow_prod_item_master_grants','table','grid_cell_notes','SELECT'),
  ('designflow_prod_item_master_grants','table','grid_cell_notes','INSERT'),
  ('designflow_prod_item_master_grants','table','grid_cell_notes','UPDATE'),
  ('designflow_prod_item_master_grants','table','grid_cell_notes','DELETE'),
  ('designflow_prod_item_master_grants','table','groups','SELECT'),
  ('designflow_prod_item_master_grants','table','itemAttachment','SELECT'),
  ('designflow_prod_item_master_grants','table','itemAttachment','INSERT'),
  ('designflow_prod_item_master_grants','table','itemAttachment','UPDATE'),
  ('designflow_prod_item_master_grants','table','itemHeader','SELECT'),
  ('designflow_prod_item_master_grants','table','itemHeader','INSERT'),
  ('designflow_prod_item_master_grants','table','itemType','SELECT'),
  ('designflow_prod_item_master_grants','table','itemType','INSERT'),
  ('designflow_prod_item_master_grants','table','licensingFeedbackReply','SELECT'),
  ('designflow_prod_item_master_grants','table','licensingFeedbackReply','INSERT'),
  ('designflow_prod_item_master_grants','table','licensingFeedbackReply','UPDATE'),
  ('designflow_prod_item_master_grants','table','licensingFeedbackReply','DELETE'),
  ('designflow_prod_item_master_grants','table','licensingStatus','SELECT'),
  ('designflow_prod_item_master_grants','table','licensingStatus','INSERT'),
  ('designflow_prod_item_master_grants','table','licensingStatus','UPDATE'),
  ('designflow_prod_item_master_grants','table','licensingStatus','DELETE'),
  ('designflow_prod_item_master_grants','table','merchGroup','SELECT'),
  ('designflow_prod_item_master_grants','table','productUserAssignment','SELECT'),
  ('designflow_prod_item_master_grants','table','productUserAssignment','INSERT'),
  ('designflow_prod_item_master_grants','table','productUserAssignment','UPDATE'),
  ('designflow_prod_item_master_grants','table','productUserAssignment','DELETE'),
  ('designflow_prod_item_master_grants','table','users','SELECT'),
  ('designflow_prod_item_master_grants','sequence','AuditLog_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','itemHeader_item_num_id_pk _seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','itemPackage_item_package_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','itemType_item_type_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','licensingFeedbackReply_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','licensingStatus_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','productUserAssignment_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','art_piece_attachment_id_seq','USAGE'),
  ('designflow_prod_item_master_grants','sequence','art_piece_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','table','DesignTeamTime','SELECT'),
  ('designflow_prod_tracking_grants','table','DesignTeamTime','UPDATE'),
  ('designflow_prod_tracking_grants','table','Factory','SELECT'),
  ('designflow_prod_tracking_grants','table','FactoryTime','SELECT'),
  ('designflow_prod_tracking_grants','table','FactoryTime','INSERT'),
  ('designflow_prod_tracking_grants','table','FactoryTime','UPDATE'),
  ('designflow_prod_tracking_grants','table','FactoryTime','DELETE'),
  ('designflow_prod_tracking_grants','table','GridAccessLevel','SELECT'),
  ('designflow_prod_tracking_grants','table','GridLayout','SELECT'),
  ('designflow_prod_tracking_grants','table','LicenseFeedBacks','SELECT'),
  ('designflow_prod_tracking_grants','table','LicensingTime','SELECT'),
  ('designflow_prod_tracking_grants','table','LicensingTime','UPDATE'),
  ('designflow_prod_tracking_grants','table','ProdOrderDetail','SELECT'),
  ('designflow_prod_tracking_grants','table','ProdOrderHeader','SELECT'),
  ('designflow_prod_tracking_grants','table','ProdOrderHeader','UPDATE'),
  ('designflow_prod_tracking_grants','table','RolePermissions','SELECT'),
  ('designflow_prod_tracking_grants','table','UDFTable','SELECT'),
  ('designflow_prod_tracking_grants','table','UIElements','SELECT'),
  ('designflow_prod_tracking_grants','table','comments','SELECT'),
  ('designflow_prod_tracking_grants','table','customers','SELECT'),
  ('designflow_prod_tracking_grants','table','deliveryLocation','SELECT'),
  ('designflow_prod_tracking_grants','table','email_logs','SELECT'),
  ('designflow_prod_tracking_grants','table','email_logs','INSERT'),
  ('designflow_prod_tracking_grants','table','externalCustomer','SELECT'),
  ('designflow_prod_tracking_grants','table','externalVendor','SELECT'),
  ('designflow_prod_tracking_grants','table','grid_cell_notes','SELECT'),
  ('designflow_prod_tracking_grants','table','grid_cell_notes','INSERT'),
  ('designflow_prod_tracking_grants','table','grid_cell_notes','UPDATE'),
  ('designflow_prod_tracking_grants','table','grid_cell_notes','DELETE'),
  ('designflow_prod_tracking_grants','table','groups','SELECT'),
  ('designflow_prod_tracking_grants','table','groups','INSERT'),
  ('designflow_prod_tracking_grants','table','groups','UPDATE'),
  ('designflow_prod_tracking_grants','table','groups','DELETE'),
  ('designflow_prod_tracking_grants','table','itemAttachment','SELECT'),
  ('designflow_prod_tracking_grants','table','itemAttachment','INSERT'),
  ('designflow_prod_tracking_grants','table','itemHeader','SELECT'),
  ('designflow_prod_tracking_grants','table','itemHeader','UPDATE'),
  ('designflow_prod_tracking_grants','table','itemLicenseImage','SELECT'),
  ('designflow_prod_tracking_grants','table','item_prod_order_detail_associations','SELECT'),
  ('designflow_prod_tracking_grants','table','licensingStatus','SELECT'),
  ('designflow_prod_tracking_grants','table','merchGroup','SELECT'),
  ('designflow_prod_tracking_grants','table','product_type_factory_time','SELECT'),
  ('designflow_prod_tracking_grants','table','product_type_factory_time','INSERT'),
  ('designflow_prod_tracking_grants','table','product_type_factory_time','UPDATE'),
  ('designflow_prod_tracking_grants','table','product_type_factory_time','DELETE'),
  ('designflow_prod_tracking_grants','table','sample','SELECT'),
  ('designflow_prod_tracking_grants','table','sample','INSERT'),
  ('designflow_prod_tracking_grants','table','sample','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_approval_event','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_approval_event','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_approval_event','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_attachment','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_attachment','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_attachment','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_box','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_box','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_box','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_box','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_carrier','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_comments','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_comments','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_comments','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_comments','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_creation_batch','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_creation_batch','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_creation_batch','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_event','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_event','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_event','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_factory_group','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_factory_group','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_factory_group','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_factory_group','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit_event','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit_event','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_factory_visit_event','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_import_job','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_import_job','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_import_job','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_import_job','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_import_row','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_import_row','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_import_row','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_import_row','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_inventory_balance','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_movement','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_movement','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_path_revision','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_path_revision','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_path_revision','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_piece_lineage','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_piece_lineage','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_piece_lineage','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_remote_request','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_remote_request','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_remote_request','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_remote_request_history','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_remote_request_history','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_remote_request_item','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_remote_request_item','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_remote_request_item','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_reservation','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_reservation','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_shipment','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_shipment','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_shipment','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_shipment','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_shipment_item','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_shipment_item','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_shipment_item','DELETE'),
  ('designflow_prod_tracking_grants','table','sample_shipment_line','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_shipment_line','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_shipment_line','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_shipment_notice','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_shipment_notice','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_shipment_notice','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_shipment_notice_recipient','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_stop_closeout','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_stop_closeout','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_stop_closeout','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_workflow','SELECT'),
  ('designflow_prod_tracking_grants','table','sample_workflow','INSERT'),
  ('designflow_prod_tracking_grants','table','sample_workflow','UPDATE'),
  ('designflow_prod_tracking_grants','table','sample_workflow','DELETE'),
  ('designflow_prod_tracking_grants','table','users','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_approval_current','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_balance_by_location','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_global_status','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_in_transit','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_open_stop_work','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_receipt_discrepancy','SELECT'),
  ('designflow_prod_tracking_grants','view','sample_visit_plan','SELECT'),
  ('designflow_prod_tracking_grants','sequence','FactoryTime_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','itemPackage_item_package_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','email_logs_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','groups_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_attachment_sample_attachment_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_box_box_id_pk_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_comments_id_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_event_event_id_pk_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_factory_group_factory_group_id_pk_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_sample_id_pk_seq','USAGE'),
  ('designflow_prod_tracking_grants','sequence','sample_shipment_item_shipment_item_id_pk_seq','USAGE'),
  ('designflow_prod_tracking_grants','function','claim_sample_shipment_notice','EXECUTE'),
  ('designflow_prod_tracking_grants','function','pack_sample_reservation','EXECUTE'),
  ('designflow_prod_tracking_grants','function','post_sample_approval_event','EXECUTE'),
  ('designflow_prod_tracking_grants','function','post_sample_movement','EXECUTE'),
  ('designflow_prod_tracking_grants','function','post_sample_piece_split','EXECUTE'),
  ('designflow_prod_tracking_grants','function','post_sample_remote_request_event','EXECUTE'),
  ('designflow_prod_tracking_grants','function','reserve_sample_remote_request_item','EXECUTE'),
  ('designflow_prod_data_sync_grants','table','ProdOrderDetail','SELECT'),
  ('designflow_prod_data_sync_grants','table','ProdOrderDetail','INSERT'),
  ('designflow_prod_data_sync_grants','table','ProdOrderHeader','SELECT'),
  ('designflow_prod_data_sync_grants','table','ProdOrderHeader','INSERT'),
  ('designflow_prod_data_sync_grants','table','ProdOrderHeader','UPDATE'),
  ('designflow_prod_data_sync_grants','table','UDFTable','SELECT'),
  ('designflow_prod_data_sync_grants','table','externalApi','SELECT'),
  ('designflow_prod_data_sync_grants','table','externalCustomer','INSERT'),
  ('designflow_prod_data_sync_grants','table','externalVendor','INSERT'),
  ('designflow_prod_data_sync_grants','table','itemAttachment','SELECT'),
  ('designflow_prod_data_sync_grants','table','itemDetail','INSERT'),
  ('designflow_prod_data_sync_grants','table','itemHeader','SELECT'),
  ('designflow_prod_data_sync_grants','table','item_prod_order_detail_associations','SELECT'),
  ('designflow_prod_data_sync_grants','table','item_prod_order_detail_associations','INSERT'),
  ('designflow_prod_data_sync_grants','table','item_prod_order_detail_associations','UPDATE'),
  ('designflow_prod_data_sync_grants','table','merchGroup','SELECT'),
  ('designflow_prod_data_sync_grants','table','merchGroupHeaders','SELECT'),
  ('designflow_prod_data_sync_grants','sequence','ProdOrderDetail_id_seq','USAGE'),
  ('designflow_prod_data_sync_grants','sequence','ProdOrderHeader_id_seq','USAGE'),
  ('designflow_prod_data_sync_grants','sequence','externalCustomer_id_seq','USAGE'),
  ('designflow_prod_data_sync_grants','sequence','externalVendor_id_seq','USAGE'),
  ('designflow_prod_data_sync_grants','sequence','itemDetail_item_pk_seq','USAGE'),
  ('designflow_prod_data_sync_grants','sequence','item_prod_order_detail_associations_id_seq','USAGE');

do $t$
declare v_role text; v_diff text; v_ok boolean;
begin
  -- Role attributes and membership shape.
  foreach v_role in array array['backend','item_master','tracking','data_sync'] loop
    if not exists (select 1 from pg_roles where rolname='designflow_prod_'||v_role||'_grants' and not rolcanlogin and not rolinherit
                   and not rolsuper and not rolcreatedb and not rolcreaterole and not rolreplication and not rolbypassrls)
    then raise exception '#2873: grant role % attributes wrong', v_role; end if;
    if not exists (select 1 from pg_roles where rolname='designflow_prod_'||v_role||'_runtime' and rolcanlogin and rolinherit
                   and not rolsuper and not rolcreatedb and not rolcreaterole and not rolreplication and not rolbypassrls
                   and rolconnlimit between 1 and 20)
    then raise exception '#2873: runtime role % attributes wrong', v_role; end if;
    if (select array_agg(r.rolname::text) from pg_auth_members m join pg_roles r on r.oid=m.roleid
        where m.member=('designflow_prod_'||v_role||'_runtime')::regrole) <> array['designflow_prod_'||v_role||'_grants']
    then raise exception '#2873: runtime role % must be a member of exactly its own grant role', v_role; end if;
    if exists (select 1 from information_schema.role_table_grants where grantee='designflow_prod_'||v_role||'_runtime')
       or exists (select 1 from pg_class c, aclexplode(c.relacl) a where a.grantee=('designflow_prod_'||v_role||'_runtime')::regrole)
    then raise exception '#2873: runtime role % holds a direct privilege', v_role; end if;
  end loop;

  -- Catalog equals the expected matrix, both directions.
  with actual as (
    select r.rolname::text grantee,
           case c.relkind when 'v' then 'view' when 'S' then 'sequence' else 'table' end kind,
           c.relname::text name, a.privilege_type priv
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    cross join lateral aclexplode(c.relacl) a join pg_roles r on r.oid=a.grantee
    where r.rolname like 'designflow\_prod\_%\_grants'
    union all
    select r.rolname::text, 'function', p.proname::text, a.privilege_type
    from pg_proc p cross join lateral aclexplode(p.proacl) a join pg_roles r on r.oid=a.grantee
    where r.rolname like 'designflow\_prod\_%\_grants'
  ), d as ((select * from actual except select * from t2873_expected) union all (select * from t2873_expected except select * from actual))
  select string_agg(format('%s %s %s %s', grantee, kind, name, priv), '; ') into v_diff from d;
  if v_diff is not null then raise exception '#2873: grant matrix drift: %', v_diff; end if;

  -- Schema boundary.
  foreach v_role in array array['backend','item_master','tracking','data_sync'] loop
    v_role := 'designflow_prod_'||v_role||'_runtime';
    if not has_schema_privilege(v_role,'dflow_prod','USAGE') or has_schema_privilege(v_role,'dflow_prod','CREATE')
    then raise exception '#2873: % schema dflow_prod privileges wrong', v_role; end if;
    if to_regnamespace('dflow') is not null and has_schema_privilege(v_role,'dflow','USAGE') then raise exception '#2873: % reaches dflow', v_role; end if;
    if to_regnamespace('plm') is not null and has_schema_privilege(v_role,'plm','USAGE') then raise exception '#2873: % reaches plm', v_role; end if;
    if to_regnamespace('hts_rag') is not null and has_schema_privilege(v_role,'hts_rag','USAGE') then raise exception '#2873: % reaches hts_rag', v_role; end if;
    if pg_has_role(v_role,'anon','USAGE') or pg_has_role(v_role,'authenticated','USAGE') or pg_has_role(v_role,'service_role','USAGE')
       or pg_has_role(v_role,'postgres','USAGE')
    then raise exception '#2873: % inherits a client or admin role', v_role; end if;
  end loop;
end $t$;

-- Live refusal controls as the Tracking runtime identity.
set local role designflow_prod_tracking_runtime;
do $r$
begin
  perform 1 from dflow_prod.sample limit 1;  -- allowed
  begin
    perform 1 from dflow_prod."RFQItem" limit 1;
    raise exception '#2873: tracking read a table outside its matrix';
  exception when insufficient_privilege then null; end;
  begin
    execute 'create table dflow_prod.t2873_forbidden(id int)';
    raise exception '#2873: tracking created a table';
  exception when insufficient_privilege then null; end;
  begin
    execute 'truncate dflow_prod.sample';
    raise exception '#2873: tracking truncated a table';
  exception when insufficient_privilege then null; end;
  if to_regnamespace('dflow') is not null then
    begin
      perform 1 from dflow.users limit 1;
      raise exception '#2873: tracking read legacy dflow';
    exception when insufficient_privilege then null; end;
  end if;
end $r$;
reset role;

-- And as the backend runtime identity: allowed read, refused sample-only write.
set local role designflow_prod_backend_runtime;
do $r$
begin
  perform 1 from dflow_prod."RFQItem" limit 1;
  begin
    execute 'truncate dflow_prod."RFQItem"';
    raise exception '#2873: backend truncated a table';
  exception when insufficient_privilege then null; end;
end $r$;
reset role;

rollback;
